export * from './ContactUsForm/ContactUsForm'
export * from './Slogan/Slogan'
export * from './OurTeam/OurTeam'
export * from './Skills/Skills'
export * from './Values/Values'
export * from './OurWork/OurWork'
export * from './ProjectDetail/ProjectSection'
export * from './Filters/Filters'